2023-04-16T10:17:44.938992+0300 ERROR An error has been caught in function 'main', process 'MainProcess' (50708), thread 'MainThread' (11240):
Traceback (most recent call last):

  File "D:\python_projects\factura\factura.py", line 331, in <module>
    main()
    └ <function main at 0x0000026BCF1EC400>

> File "D:\python_projects\factura\factura.py", line 327, in main
    get_factura()
    └ <function get_factura at 0x0000026BCF1EC360>

  File "D:\python_projects\factura\factura.py", line 106, in get_factura
    new_document_button = driver.find_element(By.XPATH, f"//a[@class='btn btn-xs btn-primarydcd']")
                          │      │            │  └ 'xpath'
                          │      │            └ <class 'selenium.webdriver.common.by.By'>
                          │      └ <function WebDriver.find_element at 0x0000026BB64CA660>
                          └ <selenium.webdriver.chrome.webdriver.WebDriver (session="00ee8ebad448a256d229574d8d8954c5")>

  File "D:\virtualenv\factura\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           │    │       │       │                       │            └ "//a[@class='btn btn-xs btn-primarydcd']"
           │    │       │       │                       └ 'xpath'
           │    │       │       └ 'findElement'
           │    │       └ <class 'selenium.webdriver.remote.command.Command'>
           │    └ <function WebDriver.execute at 0x0000026BB64C9260>
           └ <selenium.webdriver.chrome.webdriver.WebDriver (session="00ee8ebad448a256d229574d8d8954c5")>
  File "D:\virtualenv\factura\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
    │    │             │              └ {'status': 404, 'value': '{"value":{"error":"no such element","message":"no such element: Unable to locate element: {\\"metho...
    │    │             └ <function ErrorHandler.check_response at 0x0000026BB63B49A0>
    │    └ <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000026BCF12F850>
    └ <selenium.webdriver.chrome.webdriver.WebDriver (session="00ee8ebad448a256d229574d8d8954c5")>
  File "D:\virtualenv\factura\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
          │               │        │       └ ['Backtrace:', '\tGetHandleVerifier [0x0103DCE3+50899]', '\t(No symbol) [0x00FCE111]', '\t(No symbol) [0x00ED5588]', '\t(No s...
          │               │        └ None
          │               └ 'no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class=\'btn btn-xs btn-primarydcd\']"}\n  (Ses...
          └ <class 'selenium.common.exceptions.NoSuchElementException'>

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class='btn btn-xs btn-primarydcd']"}
  (Session info: chrome=112.0.5615.121)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0103DCE3+50899]
	(No symbol) [0x00FCE111]
	(No symbol) [0x00ED5588]
	(No symbol) [0x00F008F9]
	(No symbol) [0x00F00AFB]
	(No symbol) [0x00F2F902]
	(No symbol) [0x00F1B944]
	(No symbol) [0x00F2E01C]
	(No symbol) [0x00F1B6F6]
	(No symbol) [0x00EF7708]
	(No symbol) [0x00EF886D]
	GetHandleVerifier [0x012A3EAE+2566302]
	GetHandleVerifier [0x012D92B1+2784417]
	GetHandleVerifier [0x012D327C+2759788]
	GetHandleVerifier [0x010D5740+672048]
	(No symbol) [0x00FD8872]
	(No symbol) [0x00FD41C8]
	(No symbol) [0x00FD42AB]
	(No symbol) [0x00FC71B7]
	BaseThreadInitThunk [0x76456BD9+25]
	RtlGetFullPathName_UEx [0x773B8FD2+1218]
	RtlGetFullPathName_UEx [0x773B8F9D+1165]

